# Generated by Django 4.0 on 2021-12-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('Andijon viloyati', 'Andijon viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ('Fargʻona viloyati', 'Fargʻona viloyati'), ('Jizzax viloyati', 'Jizzax viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ('Qoraqalpogʻiston Respublikasi', 'Qoraqalpogʻiston Respublikasi'), ('Samarqand viloyati', 'Samarqand viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati')], max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tumanlar',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cost_choice', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('USD', 'USD')], max_length=255)),
                ('cost', models.IntegerField()),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.categorycity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Ish',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cost_choice', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('USD', 'USD')], max_length=255)),
                ('cost', models.IntegerField()),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.categorycity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cost_choice', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('USD', 'USD')], max_length=255)),
                ('cost', models.IntegerField()),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.categorycity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': "Ko'chmas  Mulk",
            },
        ),
        migrations.CreateModel(
            name='HouseGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cost_choice', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('USD', 'USD')], max_length=255)),
                ('cost', models.IntegerField()),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.categorycity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': "Uy va bog'",
            },
        ),
        migrations.CreateModel(
            name='HobbyRecreationalSports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cost_choice', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('USD', 'USD')], max_length=255)),
                ('cost', models.IntegerField()),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.categorycity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Hobbi Dam Olish Sport',
            },
        ),
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cost_choice', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('USD', 'USD')], max_length=255)),
                ('cost', models.IntegerField()),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.categorycity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Tekinga beraman',
            },
        ),
        migrations.CreateModel(
            name='FashionStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cost_choice', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('USD', 'USD')], max_length=255)),
                ('cost', models.IntegerField()),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.categorycity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Moda va Stil',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cost_choice', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('USD', 'USD')], max_length=255)),
                ('cost', models.IntegerField()),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.categorycity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Ayirboshlash',
            },
        ),
        migrations.CreateModel(
            name='ElectricalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cost_choice', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('USD', 'USD')], max_length=255)),
                ('cost', models.IntegerField()),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.categorycity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Elektr Jihozlar',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cost_choice', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('USD', 'USD')], max_length=255)),
                ('cost', models.IntegerField()),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.categorycity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Bolalar Dunyosi',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cost_choice', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('USD', 'USD')], max_length=255)),
                ('cost', models.IntegerField()),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.categorycity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Transport',
            },
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cost_choice', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('USD', 'USD')], max_length=255)),
                ('cost', models.IntegerField()),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.categorycity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Hayvonlar',
            },
        ),
    ]
